#!/bin/bash

cd {{pkg.svc_config_path}}

exec 2>&1

exec java -Dlogback.configurationFile=logback.xml \
  -XX:+UseG1GC -XX:+AggressiveOpts \
  -Xms{{cfg.jvm.heap_min}} -Xmx{{cfg.jvm.heap_max}} \
  -Dfile.encoding="{{cfg.jvm.encoding}}" -server \
  -jar {{pkg.path}}/service.jar server config.yaml
