#!/bin/bash

cd {{pkg.svc_config_path}}

exec 2>&1

exec java -Dlogback.configurationFile=logback.xml \
  -jar {{pkg.path}}/service.jar server default.yaml
# exec java -Dlogback.configurationFile={{pkg.path}}/logback.xml -jar {{pkg.path}}/service.jar server {{pkg.path}}/default.yaml
