#!/bin/bash

java -Dlogback.configurationFile=configs/logback.xml \
  -Ddd.trace.configurationFile=dd-trace.yaml \
  -javaagent:dd-java-agent.jar \
  -jar target/helloworld-1.0-SNAPSHOT.jar server configs/dev.yaml
